QT.av_private.VERSION = 5.3.2
QT.av_private.MAJOR_VERSION = 5
QT.av_private.MINOR_VERSION = 3
QT.av_private.PATCH_VERSION = 2
QT.av_private.name = QtAV
QT.av_private.libs = $$QT_MODULE_LIB_BASE
QT.av_private.includes = $$QT_MODULE_INCLUDE_BASE/QtAV/5.3.2 $$QT_MODULE_INCLUDE_BASE/QtAV/5.3.2/QtAV
QT.av_private.depends = av
QT.av_private.module_config = internal_module no_link
